### PR TITLE
overhaul httpc example

### PR DESCRIPTION
**Pull request by ksanislo**
The existing http:c example has extensive design flaws in it, this rewrite provides an overall better example that works much better.

This can handle chunked encoding, CGI content, url redirection, and dynamic/streaming download, and gives examples providing a User-Agent header, and using Keep-Alive to avoid teardown and rebuild of every connection.

### CODE REVIEW

File: network/http/source/main.c [hunk 1]
```diff
@@ -5,41 +5,133 @@
 
 #include <3ds.h>
 
-Result http_download(httpcContext *context)//This error handling needs updated with proper text printing once ctrulib itself supports that.
+Result http_download(char *url)
```
Comment (fincs) [inline network/http/source/main.c]: Should be `const char*`.

Comment (ksanislo) [inline network/http/source/main.c]: While the example uses a const char_, this is going to just get copy/pasted into a hundred things that will end up with just a char_. I don't follow the reasoning on why this should be different.

Comment (fincs) [inline network/http/source/main.c]: > this is going to just get copy/pasted into a hundred things that will end up with just a char

What makes you think so? `char*` can be passed to `const char*` parameters without problems. It is the reverse that is not possible cleanly and without avoiding compiler warnings. Const correctness must be preserved.

File: network/http/source/main.c [hunk 2]
```diff
@@ -5,41 +5,133 @@
...
-	if(ret!=0)return ret;
+		// Enable Keep-Alive connections (on by default, pending ctrulib merge)
+		// ret = httpcSetKeepAlive(&context, HTTPC_KEEPALIVE_ENABLED);
+		// printf("return from httpcSetKeepAlive: %"PRId32"\n",ret);
+		// gfxFlushBuffers();
 
-	printf("size: %"PRId32"\n",contentsize);
-	gfxFlushBuffers();
+		// Set a User-Agent header so websites can identify your application
+		ret = httpcAddRequestHeaderField(&context, (char*)"User-Agent", (char*)"httpc-example/1.0.0");
```
Comment (Lectem) [inline network/http/source/main.c]: speaking of const-correctness, why are you casting away the const here ? httpcAddRequestHeaderField takes const as input

Comment (ksanislo) [inline network/http/source/main.c]: iirc, the c++ compiler bitched continually about them until I cast them char*, and I've just copy/pasted from that code. I'll clean things up in a push in a bit here since I have to fix a memory leak with the redirection malloc() still.

Comment (Lectem) [inline network/http/source/main.c]: only problems when compiling your code without all the (char*) casts as c++ is that you get the following warning: 

> D:/devkitPro/3ds-examples/network/http/source/main.cpp:165:70: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
>  ret=http_download("http://devkitpro.org/misc/httpexample_rawimg.rgb");

which is fixed by what fincs said.
I do get other warnings with the printf though

> warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
>  printf("return from http_download: %"PRId32"\n",ret);

There are also problems with malloc (see the next comment)

File: network/http/source/main.c [hunk 3]
```diff
@@ -5,41 +5,133 @@
...
+		}
+
+		ret = httpcGetResponseStatusCode(&context, &statuscode, 0);
+		if(ret!=0){
+			httpcCloseContext(&context);
+			return ret;
+		}
+
+		if ((statuscode >= 301 && statuscode <= 303) || (statuscode >= 307 && statuscode <= 308)) {
+			newurl = malloc(0x1000); // One 4K page for new URL
```
Comment (Lectem) [inline network/http/source/main.c]: needs a cast 

>    D:/devkitPro/3ds-examples/network/http/source/main.cpp:61:19: error: invalid conversion from 'void*' to 'char*' [-fpermissive]
>    newurl = malloc(0x1000); // One 4K page for new URL

Comment (ksanislo) [inline network/http/source/main.c]: That's C++, as far as I understand the example, it's straight C in which case casting the malloc() is considered bad practice.

Comment (fincs) [inline network/http/source/main.c]: Bad practices are not acceptable. That malloc call should have a cast even though it's C code.

Comment (ksanislo) [inline network/http/source/main.c]: In C, casting that malloc() _is_ the bad practice.

Comment (fincs) [inline network/http/source/main.c]: I disagree.

Comment (ksanislo) [inline network/http/source/main.c]: If the example were a .cpp file, then yes it should be cast. But it's not.
The example with the warning has had it renamed and compiled with cpp. In C
casting the malloc() itself away from void\* is commonly considered to be a
bad idea.

**Comment by mtheall** [comment]
Add spaces around the PRI\* macros

**Comment by ksanislo** [comment]
@mtheall The original didn't have spaces around the macros, that's also a C++ vs C thing.

**Comment by fincs** [comment]
I think good C code should be compilable as-is as C++. It is pointless to introduce a gratuitous incompatibility just because some people deem it a "bad" practice. From the type system point of view, implicitly casting void\* to anything more restrictive makes no sense whatsoever. C++ fixed this aspect making it formally illegal to do so.

**Comment by ksanislo** [comment]
Jesus christ people, I'm trying to fix a downright /awful/ example of how to use HTTP because I keep running across everyone using it incorrectly...  I don't actually /care/ that much about this, it's _still_ an awful example, it just doesn't butcher http anymore.

**Comment by mtheall** [comment]
Even though this is a C-source file, I agree with fincs: it should compile with no warnings in both C and C++. The main reason being that this is example code, which inevitably means someone is going to copy/paste it into either a C or C++ project.

**Comment by ksanislo** [comment]
That's fine... its broken in the same way as the original.. Merge or not, you can fix it further.

**Comment by mtheall** [comment]
I can accept that. We can always fix the other problems ourselves.

File: network/http/source/main.c (hunk 3 above)
Comment (Lectem) [inline network/http/source/main.c]: well, if I pointed this out it's because you spoke about c++ yourself for the const-correctness

> iirc, the c++ compiler bitched continually about them until I cast them char*

It's not a big issue anyway
